"use client";

import Link from "next/link";
import Image from "next/image";
import { useState } from "react";
import AnimusArt from "./animus-art";
import "./animus-study.css";

const chrome = "https://chromewebstore.google.com/detail/animus-ai-blocker/ofpjilegndibkndcacajdgmkjicjgbck";
const firefox = "https://addons.mozilla.org/en-US/firefox/addon/animus-ai-blocker/";
const video = "https://youtube.com/shorts/8K2-XiXRt1s";

function Demo() {
  const [revealed, setRevealed] = useState(false);
  return <div className="an-demo"><div className="an-demo-bar"><span>YOUR FEED</span><span>Interactive concept</span></div><div className="an-demo-post"><span className="an-avatar">S</span><div><strong>Sample creator</strong><small>Illustrative post · AI-generated label</small></div></div><div className={`an-demo-media ${revealed ? "is-revealed" : ""}`} aria-live="polite">{revealed ? <><div className="an-abstract"><i/><i/><i/></div><strong>Content revealed for this preview</strong><p>You decide what to see.</p></> : <><span className="an-cover-symbol">◈</span><strong>AI content filtered</strong><p>Why: an explicit AI-generation label</p></>}<button onClick={() => setRevealed(!revealed)}>{revealed ? "Cover again" : "Show once"}</button></div><p className="an-note">A simplified interaction prototype, not a live detector. No feed data is accessed.</p></div>;
}

function Shot({ name, alt, mobile = false }: {name: string; alt: string; mobile?: boolean}) {
  return <Image src={`/animus/${name}.png`} alt={alt} width={mobile ? 400 : 1280} height={mobile ? 820 : 800} sizes={mobile ? "(max-width: 700px) 44vw, 240px" : "(max-width: 700px) 90vw, 1100px"} className="an-shot"/>;
}

export default function AnimusStudy() {
  return <main className="an-study" id="an-top">
    <header className="an-nav"><Link href="/">Faiza Khan <span>UX / Product designer</span></Link><Link href="/#work">← All work</Link></header>
    <section className="an-hero an-wrap"><div><p className="an-eyebrow">ANIMUS AI BLOCKER / DESIGN + DEVELOPMENT</p><h1>Your feed.<br/>Your <em>choice.</em></h1><p className="an-lead">A little less synthetic noise. A little more control over what you see.</p><p>Designing a reversible way to filter declared AI media, from browser extensions to a mobile beta.</p><a className="an-text-link" href="#an-story">Explore the story <span>↓</span></a></div><AnimusArt/><dl className="an-facts"><div><dt>My contribution</dt><dd>UX, interface design + development</dd></div><div><dt>Build approach</dt><dd>Development with ChatGPT Codex</dd></div><div><dt>Available on</dt><dd>Chrome + Firefox</dd></div><div><dt>Next chapter</dt><dd>Mobile app in beta testing</dd></div></dl></section>
    <div className="an-ticker" aria-hidden="true"><span>LESS NOISE</span><i>✳</i><span>MORE AGENCY</span><i>✳</i><span>ALWAYS A WAY BACK</span></div>
    <div className="an-wrap" id="an-story">
      <section className="an-section an-split"><div><p className="an-eyebrow">01 / UNDERSTAND</p><h2>The problem isn’t AI.<br/>It’s losing the choice.</h2></div><div><p>Social feeds mix human-made and synthetic media in the same scroll. For someone who wants less declared AI content, opting out can become a repetitive, post-by-post task.</p><p>Animus explores a different relationship with the feed: an unobtrusive cover, a reason for the decision, and a way to undo it.</p><p className="an-note">This case study draws on the published product and supplied demo screens. It does not present interview findings or claim a measured change in user behaviour.</p></div></section>
      <div className="an-question"><p className="an-eyebrow">THE DESIGN CHALLENGE</p><h2>How might we reduce unwanted content<br/>without taking control away?</h2><span>Filter with a reason. Leave room for a choice.</span></div>
      <section className="an-section"><div className="an-section-head"><p className="an-eyebrow">02 / DEFINE</p><h2>Trust is the feature.</h2><p>Three principles make the experience understandable, not just functional.</p></div><div className="an-three"><article><span className="an-number">01</span><h3>Explain the cover</h3><p>A hidden post should not feel like a disappearing post. Keep the reason close to the action.</p></article><article><span className="an-number">02</span><h3>Make it reversible</h3><p>Curiosity is not an error. Revealing content should be an ordinary part of the experience.</p></article><article><span className="an-number">03</span><h3>Respect uncertainty</h3><p>Do not make a stronger claim than the evidence supports. A visible post is not a certificate of authenticity.</p></article></div></section>
      <section className="an-section"><div className="an-section-head"><p className="an-eyebrow">03 / EXPLORE</p><h2>Before the polish,<br/>a clear path through.</h2><p>Low-fidelity reconstructions created for this case study to explain the interaction structure, not original project artifacts.</p></div><div className="an-wireframes">
        <article><div className="an-wire"><header>Protection settings <span>×</span></header><h4>Choose where it works</h4><p>Keep control site by site.</p>{["X", "Instagram", "Other supported sites"].map(x => <div className="an-wire-row" key={x}>{x}<i/></div>)}<div className="an-wire-button">Save preferences</div><small>Protection can be turned off.</small></div><h3>01 / Set the boundaries</h3><p>Start with scope, not a wall of switches.</p></article>
        <article><div className="an-wire"><header>Social feed <span>•••</span></header><div className="an-wire-lines"><i/><i/></div><div className="an-wire-cover"><span>◇</span><h4>AI content filtered</h4><p>Explain why it was covered</p><div className="an-wire-button">Show once</div></div><div className="an-wire-lines"><i/><i/></div></div><h3>02 / Keep context intact</h3><p>Place the explanation where the content was.</p></article>
        <article><div className="an-wire"><header>Revealed post <span>•••</span></header><div className="an-wire-placeholder">CONTENT</div><h4>Back in your hands</h4><div className="an-wire-button">Cover again</div><div className="an-wire-row">Correct a decision <span>↗</span></div><small>Recovery belongs in the flow.</small></div><h3>03 / Offer a way back</h3><p>Explore reveal and correction states together.</p></article>
      </div></section>
      <section className="an-section an-split an-prototype"><div><p className="an-eyebrow">04 / PROTOTYPE</p><h2>A pause.<br/>Not a dead end.</h2><p>The cover becomes a small decision point. A short explanation provides context; one visible action lets the person continue.</p><p>Try the reconstructed interaction. The revealed artwork is an abstract placeholder, not a real social post.</p><div className="an-inline-note">An intentional constraint: the interface should remain useful even when a filtering decision needs to be reversed.</div></div><Demo/></section>
      <section className="an-section"><div className="an-section-head"><p className="an-eyebrow">05 / INTERFACE</p><h2>Quiet controls.<br/>Inside a noisy feed.</h2><p>Actual product captures: setup, an X feed and an Instagram grid. These show the product at the time of capture; wording and capabilities may differ between releases.</p></div><figure className="an-desktop-main"><Shot name="desktop-setup" alt="Animus desktop setup with evidence-first protection settings"/><figcaption>Set expectations before asking someone to enable protection.</figcaption></figure><div className="an-desktop-pair"><figure><Shot name="desktop-x" alt="X feed with Animus reversible filtering notices"/><figcaption>X / The reason and reveal action stay in the feed.</figcaption></figure><figure><Shot name="desktop-instagram" alt="Instagram grid with selected media replaced by Animus notices"/><figcaption>Instagram / The same control adapts to a different layout.</figcaption></figure></div></section>
      <section className="an-section an-mobile"><div className="an-section-head"><p className="an-eyebrow">06 / EXTEND TO MOBILE</p><h2>Same principle.<br/>A more personal screen.</h2><p>The mobile app is in beta testing. These supplied demo frames show setup, permission disclosure, and covers inside X and Instagram.</p></div><div className="an-phone-grid">{[["mobile-setup","01 / Set up protection","Mobile beta protection settings"],["mobile-permission","02 / Explain access","Mobile permission disclosure explaining local label checking"],["mobile-x-redacted","03 / Cover an X post","Mobile X post with user identities redacted and a reversible Animus cover"],["mobile-instagram","04 / Keep a reveal action","Mobile Instagram cover with Show once action"]].map(([name, caption, alt]) => <figure key={name}><div className="an-phone"><Shot name={name} alt={alt} mobile/></div><figcaption>{caption}</figcaption></figure>)}</div><div className="an-split an-mobile-notes"><h3>Permission is part of the experience.</h3><p>The beta introduces a more sensitive moment: explaining accessibility access before it is enabled. The UX challenge is to make scope, local processing and user control understandable without burying the decision. Recording controls and beta UI are retained in these demo frames.</p></div></section>
      <section className="an-section an-split"><div><p className="an-eyebrow">07 / BUILD</p><h2>From design decisions<br/>to working behaviour.</h2></div><div><p>I also worked on development using ChatGPT Codex, connecting the interface work with implementation rather than stopping at the visual handoff.</p><p>For a product that lives inside other interfaces, the important details sit between design and code: where a cover fits, how an action restores content, and how settings communicate what is active.</p><div className="an-build-loop"><span>Design</span><b>↔</b><span>Build with Codex</span><b>↔</b><span>Refine</span></div></div></section>
      <section className="an-section"><div className="an-section-head"><p className="an-eyebrow">08 / VALIDATE + ITERATE</p><h2>What needs to earn trust next.</h2><p>Mobile beta testing is ongoing. The checks below are proposed evaluation priorities, not completed research results.</p></div><div className="an-three"><article><h3>Comprehension</h3><p>Can someone explain why a post was covered, and what Animus cannot determine?</p><small>Check: explain the notice in their own words.</small></article><article><h3>Recovery</h3><p>Can someone reveal content and find the relevant protection control without help?</p><small>Check: task completion and points of hesitation.</small></article><article><h3>Resilience</h3><p>Does the cover stay attached to the right content as the feed changes?</p><small>Check: scrolling, navigation and layout changes.</small></article></div></section>
      <section className="an-section an-release"><p className="an-eyebrow">THE OUTCOME SO FAR</p><h2>Out of the canvas.<br/><em>Into the browser.</em></h2><div className="an-release-grid"><div><strong>Chrome</strong><span>Published extension</span></div><div><strong>Firefox</strong><span>Published extension</span></div><div><strong>Mobile</strong><span>Beta testing</span></div></div><p>The milestone is a working product in real browsing contexts, with a mobile beta opening the next round of learning and refinement.</p><div className="an-links"><a href={chrome} target="_blank" rel="noreferrer">View on Chrome ↗</a><a href={firefox} target="_blank" rel="noreferrer">View on Firefox ↗</a><a href={video} target="_blank" rel="noreferrer">Watch the mobile demo ↗</a></div></section>
      <section className="an-source-note"><h3>A note on scope and materials</h3><p>Animus is not a universal AI detector. The <a href={chrome}>Chrome listing</a> describes declaration and supported provenance filtering; the <a href={firefox}>Firefox listing</a> describes label-based filtering without visual models or Content Credentials verification. Desktop extensions and the mobile beta are separate products.</p><p>Product screens were supplied for this portfolio. The 3D illustration, wireframes and interactive preview were created to explain the experience. Evaluation priorities are forward-looking; measured usability outcomes are not yet presented.</p><p>For more about my contribution and project decisions, <a href="mailto:faizakhan1012@gmail.com">get in touch</a>. Follow product updates on <a href="https://x.com/AnimusAIBlocker">X</a>.</p></section>
      <footer className="an-footer"><Link href="/#work">← All work</Link><a href="#an-top">Back to top ↑</a></footer>
    </div>
  </main>;
}
