import "./home-personality.css";

export function StudioSculpture() {
  return <div className="fk-studio" aria-hidden="true"><div className="fk-studio-grid"/><div className="fk-studio-orbit"/><div className="fk-torus"/><div className="fk-sphere"/><div className="fk-cube"><i/><i/><i/></div><div className="fk-mini-window"><div className="fk-mini-bar"><i/><i/><i/><span>IDEAS IN PLAY</span></div><div className="fk-mini-content"><span>Make it<br/><em>feel right.</em></span><div className="fk-mini-swatches"><i/><i/><i/></div></div></div><div className="fk-studio-label">A little logic. A little imagination.</div></div>;
}

export function ExperienceStrip() {
  return <section className="fk-experience-strip" aria-label="Experience at a glance"><div><strong>4+</strong><span>years in UX & product design</span></div><div><strong>Enterprise UX</strong><span>Complex products. Human-centred solutions.</span></div><div><strong>Design ↔ Build</strong><span>Computer science meets creative craft</span></div></section>;
}

function ControllerArt() {
  return <svg className="fk-controller" viewBox="0 0 320 190" fill="none" aria-hidden="true"><defs><linearGradient id="fk-pad" x1="90" y1="35" x2="230" y2="170" gradientUnits="userSpaceOnUse"><stop stopColor="#fff"/><stop offset=".45" stopColor="#e0d6ff"/><stop offset="1" stopColor="#8871bf"/></linearGradient></defs><ellipse cx="158" cy="158" rx="100" ry="15" fill="#725c9420"/><path d="M92 42c-22 3-35 40-41 72-5 26 3 45 20 45 16 0 24-26 41-28h91c16 2 23 28 40 28 18 0 25-17 20-43-6-35-20-71-42-74-24-3-102-3-129 0Z" fill="#9c87c9" transform="translate(0 7)"/><path d="M92 42c-22 3-35 40-41 72-5 26 3 45 20 45 16 0 24-26 41-28h91c16 2 23 28 40 28 18 0 25-17 20-43-6-35-20-71-42-74-24-3-102-3-129 0Z" fill="url(#fk-pad)" stroke="#f8f2ff" strokeWidth="2"/><path d="M90 68h12v15h15v12h-15v15H90V95H75V83h15Z" fill="#4b3e66"/><circle cx="220" cy="73" r="7" fill="#f29c87"/><circle cx="236" cy="90" r="7" fill="#a3cfc2"/><circle cx="204" cy="90" r="7" fill="#aea1e0"/><circle cx="220" cy="106" r="7" fill="#f1d496"/><circle cx="134" cy="112" r="14" fill="#716184"/><circle cx="179" cy="112" r="14" fill="#716184"/><circle cx="134" cy="110" r="10" fill="#8e7ca0"/><circle cx="179" cy="110" r="10" fill="#8e7ca0"/><rect x="145" y="67" width="23" height="6" rx="3" fill="#8a7c9e"/></svg>;
}

export function AboutFaiza() {
  return <section id="about" className="fk-about"><div className="fk-about-intro"><div><p className="eyebrow">The person behind the pixels</p><h2>A designer’s eye.<br/><em>A builder’s curiosity.</em></h2><div className="fk-signature"><span>Faiza Khan</span><small>also around the internet as KFstarLs</small></div></div><div className="fk-about-copy"><p>I’m a UX and Product Designer with 4+ years of experience, including four years as a UX consultant at Capgemini.</p><p>I’ve worked on enterprise platforms, AI-assisted workflows and design systems, turning complex requirements into experiences that make sense to the people using them.</p><p>Outside enterprise UX, my freelance work spans graphic design. It brings a different kind of attention to my work: composition, identity, and how the small details make something feel considered.</p><p>With a background in computer science, I enjoy getting closer to how things are built, too. Animus is one expression of that curiosity, bringing design and development together with ChatGPT Codex.</p><div className="fk-about-links"><a href="/resume" target="_blank" rel="noreferrer">View my résumé ↗</a><a href="https://www.linkedin.com/in/faiza-khan-348a9818b/" target="_blank" rel="noreferrer">Connect on LinkedIn ↗</a></div></div></div>
    <div className="fk-experience-board"><div><p className="eyebrow">A foundation in making things work</p><h3>From engineering logic<br/>to human experiences.</h3><p>A B.Tech engineer in Computer Science, with a frontend internship and a path into UX consulting. Different perspectives, connected by the same curiosity.</p></div><ol><li><span>01</span><div><strong>Technical foundation</strong><p>Computer science and hands-on frontend experience.</p></div></li><li><span>02</span><div><strong>Four years at Capgemini</strong><p>Progressed from Analyst to Senior Analyst to Associate Consultant in UX.</p></div></li><li><span>03</span><div><strong>A broader creative practice</strong><p>Freelance graphic design and independently built products.</p></div></li></ol></div>
    <div className="fk-curiosity-heading"><p className="eyebrow">Always a work in progress</p><h2>Where my curiosity goes next.</h2><p>Some things I do. Some things I’m learning. All part of how I see design.</p></div><div className="fk-interest-grid"><article className="fk-interest fk-interest-game"><div className="fk-interest-art"><ControllerArt/></div><span className="fk-interest-label">An industry I’m drawn to</span><h3>Gaming UX</h3><p>I’m interested in bringing my UX practice into games, exploring the interfaces and interactions that help people feel immersed, capable and in control.</p></article><article className="fk-interest fk-interest-3d"><div className="fk-interest-art" aria-hidden="true"><div className="fk-model-stack"><span><i/><i/><i/></span><span><i/><i/><i/></span><span><i/><i/><i/></span></div></div><span className="fk-interest-label">Currently learning on my own</span><h3>Thinking in 3D</h3><p>Teaching myself 3D design, experimenting with form, depth and materials, and finding new ways to bring a little character to the screen.</p></article><article className="fk-interest fk-interest-package"><div className="fk-interest-art" aria-hidden="true"><div className="fk-graphic-poster"><span>Aa</span><div><i/><i/><i/></div><small>FORM / TYPE / COLOUR</small></div></div><span className="fk-interest-label">Part of my freelance practice</span><h3>Beyond the interface</h3><p>Graphic design gives me space to explore visual identity, typography and composition.</p></article></div>
    <div className="fk-toolbox"><span>A few tools in my toolkit</span><div>{["Figma", "FigJam", "Adobe XD", "Illustrator", "Photoshop", "Procreate", "HTML / CSS", "React", "ChatGPT Codex"].map(tool=><span key={tool}>{tool}</span>)}</div></div>
  </section>;
}
