// User-supplied case-study copy. Preserve wording; presentation lives in the component.
export const caseStudyCopy = [
  "A SaaS Solution",
  "With millions of possible vehicle configurations, forecasting customer demand has become a complex challenge for automotive manufacturers. Buyers now expect cars tailored to their individual tastes, making personalization a standard expectation and adding complexity to production planning.",
  "Project Overview",
  "Predicting what customers will choose before they place an order was the central goal of this project for an Italian motorcycle manufacturing company (one of the world’s largest automotive manufacturers).We also adapted this solution for a leading global IT and computing company. Explore the related case study. As vehicle customization becomes increasingly common, manufacturers must anticipate demand across an enormous range of combinations, each reflecting different customer preferences.",
  "As the project’s sole UX consultant, I led the design of an internal simulation tool to help the manufacturer manage this complexity. The aim was to make it easier to anticipate customer orders and support planning within a highly complex manufacturing environment.",
  "(Note: Due to confidentiality, the client name and final UI visuals are withheld, but this case study covers our complete design process.)",
  "Problem statement",
  "Building customized vehicles to order is great for the customer, but incredibly difficult for the supply chain. With vehicles requiring tens of thousands of physical parts and offering thousands of unique feature combinations, it is nearly impossible for planners to forecast exact component demand. Supply chain teams needed a tool to accurately simulate future orders so they could manufacture efficiently, rather than wasting millions of dollars guessing what parts to keep in stock.",
  "Excess Inventory",
  "Uncertain demand across 30,000+ car parts and 2,000+ bike parts leaves surplus stock sitting unused.",
  "Long Delivery Times",
  "Products take months to move from manufacturing to stores, keeping customers waiting.",
  "Limited Personalization",
  "Premium products offer fewer customization options than customers expect.",
  "Unfulfilled Orders",
  "Shortages of essential parts prevent customer orders from being fulfilled.",
  "Slow Planning",
  "Traditional planning cycles delay decisions and demand forecasts.",
  "Our Solution",
  "Our team worked on the Gen AI Powered Order Simulation (SaaS), a predictive analytics tool which is an order based system that uses statistical forecasting methods GenAI, and machine learning algorithms to generate predictions for specific vehicle configurations using historical data. Additionally, the forecast can be fine tuned by incorporating assumptions about future changes.",
  "Key Design Goals",
  "Following deep-dive workshops and system analyses, our core objective was clear: transform a slow, multi-week process into an effortless, hours-long workflow.",
  "Streamline Demand Forecasting: Harness historical trends and predictive algorithms to simplify complex order predictions.",
  "Flexible Scenario Modeling: Allow planners to tweak parameters and run custom simulations using conditional logic and volume adjustments.",
  "Seamless Data Exporting: Equip users with direct file export features to easily push simulation results into external BI tools and reports.",
  "Accelerate Planning Cycles: Drastically shorten decision-making timelines, compressing weeks of manual effort into a few hours.",
  "Build System Trust & Clarity: Provide clear option-level breakdowns and AI confidence metrics so users understand and trust the results.",
  "Enable Cross-Team Collaboration: Incorporate built-in survey capabilities for sales teams across different regions and organizational tiers to gather real-time ground demand insights.",
  "Technical Stack & Integration",
  "SAP BTP (Business Technology Platform) as the base",
  "Angular for a responsive, modern UI frontend",
  "SAP Fiori design principles partially referenced",
  "Export compatibility with external BI tools",
  "Integration with demand planning modules and supplier alerting systems",
  "GenAI (cluster analysis) & ML modules (for pattern learning and simulation calibration)",
  "Design Process: Understanding, Creating & Refining",
  "01 - Discovery & Research",
  "I researched the planning process to understand how supply chain teams used order trends to inform production decisions. I created initial user flows to map their journey, identify key decision points, and understand where simulations could support their work.",
  "02 - Workflow Mapping & Brainstorming",
  "Through brainstorming and detailed workflow mapping, I explored how users would move between volume planning, running simulations, adjusting configuration forecasts, and exporting results. This helped define the tool’s structure and the steps needed to complete each task.",
  "? Images for workflow ?",
  "03 - Sketches & Low-Fidelity Screens",
  "I translated the workflows into sketches and low-fidelity screens, exploring layouts for dashboards, simulation inputs, and results. These early designs helped me refine the information hierarchy and interactions before developing the visual details.",
  "? Images for sketches ?",
  "04 - High-Fidelity Designs & Prototyping",
  "I developed detailed mockups and interactive prototypes to show how the tool would look and behave. Connecting the screens made it possible to walk through key tasks and review the experience with stakeholders before development.",
  "? Images for high fidelity screens ?",
  "05 - Usability Testing & Refinement",
  "I conducted usability and accessibility testing to identify unclear interactions and barriers to completing tasks. Based on the findings, I added bulk order simulation features that reduced repetitive data entry, making it faster and easier for users to run multiple simulations.",
  "I also acted as a bridge between stakeholders and the development team, translating feedback into clear design changes and helping developers understand the updates needed and the reasoning behind them.",
  "? Images for updated screen ?",
  "Outcomes & Impact",
  "The solution brought forecasting, planning, and simulation into one workflow, helping teams anticipate demand and manage complex product configurations.",
  "Faster Planning",
  "Planning activities that previously took weeks could be completed in hours, supporting quicker procurement and production decisions.",
  "Less Manual Work",
  "Bulk simulation features reduced repeated data entry, making it easier to explore multiple order scenarios.",
  "Illustrative metric: 40% less time spent setting up simulations.",
  "Better Inventory Planning",
  "Clearer forecasts helped teams align parts availability with expected demand, reducing excess stock and the risk of shortages.",
  "Illustrative metric: 20% reduction in surplus inventory.",
  "More Confident Decisions",
  "A shared view of simulation results helped planners compare options and make informed decisions about future production needs.",
  "Faster Order Fulfilment",
  "Better visibility into required parts supported production readiness and shorter waits for customers ordering personalized vehicles.",
  "Illustrative metric: 15% reduction in order fulfilment time."
];
