import Link from "next/link";
import ConfidentialityNote from "./confidentiality-note";
import Image from "next/image";
import botIcon from "../../public/supply-chain-assistant/bot-icon.png";
import conceptSketch from "../../public/supply-chain-assistant/concept-sketch.png";
import lowFidelity from "../../public/supply-chain-assistant/low-fidelity.png";
import highFidelity from "../../public/supply-chain-assistant/high-fidelity.png";
import gatewayPlacement from "../../public/supply-chain-assistant/gateway-placement.png";
import "./supply-chain-assistant-study.css";

function FeedbackThumb({ down = false }: { down?: boolean }) {
  return <svg className="sca-feedback-thumb" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><g transform={down ? "rotate(180 12 12)" : undefined}><path d="M7 10v11H3V10h4Zm0 0 5-7c.5-.7 1.7-.5 2 .3.5 1.3.4 2.6 0 3.9L13.5 9H19a2 2 0 0 1 2 2.4l-1.5 7.8A2.2 2.2 0 0 1 17.3 21H7"/></g></svg>;
}

function BotSculpture() {
  return <div className="sca-sculpture" aria-hidden="true"><div className="sca-orbit"/><div className="sca-float sca-float-a">Ask in your language <span>↗</span></div><div className="sca-bot"><div className="sca-antenna"/><div className="sca-face"><i/><i/><span/></div></div><div className="sca-float sca-float-b"><span>≡</span> Answers with context</div><div className="sca-spark">✦</div><div className="sca-pedestal"/></div>;
}

const journey = [
  ["Open", "Find the assistant on any gateway page and open the chat panel."],
  ["Ask", "Describe a question naturally, in the language you prefer."],
  ["Read", "Receive an answer relevant to the question and your role."],
  ["Check", "Inspect the references behind the response when more context is needed."],
  ["Respond", "Copy useful information, give feedback, or continue the conversation."],
];

export default function SupplyChainAssistantStudy() {
  return <main className="sca-study" id="sca-top">
    <div className="sca-nav-wrap"><nav className="sca-nav" aria-label="Case study navigation"><Link href="/">Faiza Khan<span>UX / Product designer</span></Link><Link href="/#work">← All work</Link></nav></div>
    <header className="sca-hero"><div className="sca-shell"><div className="sca-hero-grid"><div><p className="sca-eyebrow">Generative AI · Supply Chain Assistant</p><h1>Less searching.<br/>More <em>conversation.</em></h1><p className="sca-intro">A familiar place to ask. A clearer way to find answers.<br/>Conversational support, built into the supplier gateway.</p><a className="sca-cta" href="#sca-context">Explore the story <span>↓</span></a></div><div className="sca-art"><BotSculpture/><p>Concept illustration · Not the original product icon</p></div></div><dl className="sca-facts"><div><dt>My role</dt><dd>End-to-end UX design</dd></div><div><dt>Team delivery</dt><dd>2 months, from planning to use</dd></div><div><dt>Design scope</dt><dd>Conversation · UX · UI · Iconography</dd></div><div><dt>Validation</dt><dd>Accessibility · Usability · UI testing</dd></div></dl></div></header>
    <div className="sca-shell sca-story">
      <section id="sca-context" className="sca-section"><div className="sca-heading"><div><p className="sca-eyebrow">The next chapter of the gateway</p><h2>Access was simpler.<br/>Finding answers was next.</h2></div><p>The gateway brought applications together. Suppliers still needed a way to find relevant guidance within documents and across the tools they used - without turning every question into a support request.</p></div><div className="sca-context-grid"><article><span>01 / Discovery</span><h3>Information takes effort to find.</h3><p>Long documents can leave a simple question buried beneath pages of detail.</p></article><article><span>02 / Language</span><h3>One supplier network. Many languages.</h3><p>Support needs to work across languages and time zones, not just office hours.</p></article><article><span>03 / Relevance</span><h3>Different roles need different answers.</h3><p>The useful response is the one that helps with the task in front of the user.</p></article></div><Link className="sca-link" href="/work/supplier-gateway">See the gateway case study ↗</Link></section>
      <section className="sca-question"><p className="sca-eyebrow">The design question</p><h2>How might we make asking for help feel effortless - while keeping the answer open to scrutiny?</h2></section>
      <section className="sca-section sca-ownership"><div><p className="sca-eyebrow">My contribution</p><h2>From the first idea<br/>to the final interaction.</h2><p>I worked across the full UX lifecycle: planning and brainstorming, conversational flows, interface design, bot icons and supporting iconography, through accessibility, usability, and UI testing.</p></div><aside><strong>2<span>months</span></strong><p>The team took the feature from planning and brainstorming through development, delivery, UAT, and into user adoption within two months.</p><div className="sca-process"><span>Plan & explore</span><b>→</b><span>Design & build</span><b>→</b><span>Test & deliver</span></div><small>One end-to-end delivery window, with design and development working together.</small></aside></section>
      <section className="sca-section"><div className="sca-heading"><div><p className="sca-eyebrow">An extension, not another destination</p><h2>Help stays close<br/>to the work.</h2></div><p>A bot entry point is available across gateway pages. Clicking it opens a chat pop-up, keeping the conversation alongside the user’s current task.</p></div><figure className="sca-placement-screen sca-placement-board"><div className="sca-placement-labels"><div className="sca-placement-callout"><strong>The workspace stays in view</strong><p>Ask for help alongside the applications you use.</p><span aria-hidden="true">↓</span></div><div className="sca-placement-callout"><strong>A conversation alongside the task</strong><p>The pop-up opens on the right, within the gateway.</p><span aria-hidden="true">↓</span></div></div><Image src={gatewayPlacement} alt="Blurred full gateway screen showing the chat pop-up beside the application workspace" sizes="(max-width: 900px) 100vw, 900px"/><div className="sca-placement-launcher-note"><span aria-hidden="true">↑</span><strong>One familiar entry point</strong><p>The bot button is available across gateway pages.</p></div><figcaption>The chat pop-up within the gateway workspace.</figcaption></figure></section>
      <section className="sca-section sca-flow-section"><div className="sca-heading"><div><p className="sca-eyebrow">The conversational journey</p><h2>A question is only<br/>the beginning.</h2></div><p>The flow continues beyond receiving a response: users can inspect the source, take the information with them, and signal whether it helped.</p></div><ol className="sca-user-flow">{journey.map(([title, copy], i) => <li key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol><div className="sca-return-path"><span aria-hidden="true">↶</span> Need more detail? Ask a follow-up and continue the conversation.</div></section>
      <section className="sca-trust"><div className="sca-heading"><div><p className="sca-eyebrow">Designing for informed use</p><h2>An answer, with<br/>room to question it.</h2></div><p>The response controls appear on hover: positive and negative feedback, copy, and an information icon. A subtle AI-content notice reminds users that an answer may be incorrect.</p></div><div className="sca-trust-grid"><div className="sca-response-model"><div className="sca-response-heading"><Image className="sca-response-bot" src={botIcon} alt="" sizes="56px"/><span className="sca-response-label">Answer-level interactions</span></div><div className="sca-response-lines" aria-hidden="true"><i/><i/><i/></div><div className="sca-response-tools" aria-label="Illustration of response actions"><span>⧉ <small>Copy</small></span><span><FeedbackThumb/> <small>Helpful</small></span><span><FeedbackThumb down/> <small>Not helpful</small></span><span>ⓘ <small>References</small></span></div><p>AI-generated content may be incorrect.</p><div className="sca-source-card"><span>ⓘ</span><div><strong>Where did this come from?</strong><p>References point back to the internal content used for the answer.</p></div></div><small className="sca-concept-note">Interaction model · Illustrative, not a product screenshot</small></div><div className="sca-trust-notes"><article><span>01</span><div><h3>Make the origin visible.</h3><p>The information control reveals references to relevant internal pages or files, including content from connected inbox and inventory tools.</p></div></article><article><span>02</span><div><h3>Make feedback lightweight.</h3><p>Thumbs-up and thumbs-down controls let users respond to an individual answer, without interrupting the conversation.</p></div></article><article><span>03</span><div><h3>Make uncertainty explicit.</h3><p>The AI notice sets an important expectation: a generated answer is useful assistance, not a guarantee of correctness.</p></div></article></div></div></section>
      <section className="sca-section"><div className="sca-heading"><div><p className="sca-eyebrow">The craft behind the conversation</p><h2>Small details.<br/>A coherent experience.</h2></div><p>Alongside the conversation and interface, I designed the bot icons and supporting iconography, and worked through accessibility, usability, and UI testing.</p></div><div className="sca-quality-grid"><article><span>✦</span><h3>Iconography</h3><p>Bot identity and action icons were part of the UX work, not an afterthought.</p></article><article><span>↔</span><h3>Usability</h3><p>The entry point, chat panel, and answer controls formed one connected experience to test.</p></article><article><span>◎</span><h3>Accessibility & UI</h3><p>Accessibility and interface testing were included in the design scope through delivery.</p></article></div></section>
      <section className="sca-section sca-artifacts"><div className="sca-heading"><div><p className="sca-eyebrow">Design development</p><h2>From exploration<br/>to interface.</h2></div><p>The conversation takes shape, from a conceptual sketch to a low-fidelity layout and the high-fidelity interface.</p></div><div className="sca-design-stages">{[{title:"Conceptual sketch",image:conceptSketch,alt:"Conceptual sketch of the assistant conversation panel"},{title:"Low-fidelity screen",image:lowFidelity,alt:"Low-fidelity assistant layout with message bubbles and response controls"},{title:"High-fidelity screen",image:highFidelity,alt:"Blurred high-fidelity assistant chat interface"}].map(({title,image,alt}) => <figure key={title}><figcaption>{title}</figcaption><Image src={image} alt={alt} sizes="(max-width: 600px) 50vw, 280px"/></figure>)}</div></section>
      <section className="sca-results"><div><p className="sca-eyebrow">Reported post-launch outcomes</p><h2>Less support effort.<br/>More efficient work.</h2></div><dl><div><dt>20%</dt><dd>decrease in support workload</dd></div><div><dt>80%</dt><dd>improvement in operational efficiency</dd></div></dl><p>Measured after launch and reported at the assistant-project level. These results reflect the combined product and team effort, not UX changes in isolation.</p></section>
      <section className="sca-ending"><p className="sca-eyebrow">Delivered together</p><h2>A new way to ask.<br/><em>Right where suppliers work.</em></h2><p>Within a two-month team delivery cycle, the assistant moved from planning to use. The UX connected a persistent entry point, natural-language conversation, and answer-level controls into one gateway experience.</p><div><span>Embedded support</span><span>Multilingual conversation</span><span>References & feedback</span></div></section>
    <ConfidentialityNote/>
      <footer className="sca-footer"><Link href="/#work">← All work</Link><Link href="/work/supplier-gateway">The gateway story ↗</Link><a href="#sca-top">Back to top ↑</a></footer>
    </div>
  </main>;
}
